[package]
name = "gedcomx_date"
version = "0.0.2"
authors = ["Nicolas Barbotte <nicolas@barbotte.net>"]

description = "Gedcomx Date Parser"

license = "MIT"
readme = "README.md"

[dependencies]
nom = {version = "4", features = ["verbose-errors"]}

[features]
default = []
dev = []
bench = []
